source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LGSemiModalNavController_Example', :exclusive => true do
  pod "LGSemiModalNavController", :path => "../"
end

target 'LGSemiModalNavController_Tests', :exclusive => true do
  pod "LGSemiModalNavController", :path => "../"

  
end
